### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by kenperkins** [CircleCI-Public/aws-s3-orb#16]
I'm currently upgrading from `1.0.16` to `1.1.1` as a result of #13 getting merged, but I noticed there are no release notes, no change log and no way of _knowing_ without analyzing the source myself. So this request would be to add a change log and use git tags aligned with the orb version so it's easier to see the diffs.

**Comment by gmemstr** [comment]
This is definitely a conversation we have been having internally, and we have implemented it into our [Orb Project Template](https://github.com/CircleCI-Public/Orb-Project-Template) to encourage implementation in newer orbs. It's a little tricky to do retroactively or for older orbs, but it is something we're aiming add to our own orbs moving forward!

**Comment by FelicianoTech** [comment]
A changelog is a bit harder for us to do right now but I can definitely enable Git tags to work for this repo. I'll update here when that happens.

**Comment by devkapilbansal** [comment]
@kenperkins I want to work on this issue

**Comment by gmemstr** [comment]
Assigning to @felicianotech for the time being.

**Comment by FelicianoTech** [comment]
So this isn't a changelog but the ability to have git tags has been turned on i #18.

**Comment by gmemstr** [comment]
Going to go ahead and close this - we're working on a chagelog process for orbs, and we should have more to share soon :)
