### ISSUE TITLE
[FEATURE] Support AWS endpoint

### ISSUE THREAD

**Issue by atmosx** [CircleCI-Public/aws-s3-orb#21]
**Is your feature request related to a problem? Please describe.**
I want to use this ORB with [Digital Ocean Spaces](https://www.digitalocean.com/products/spaces/). DO spaces is an s3-compatible object store.

**Describe the solution you'd like**
I would like to use a variable to setup the default AWS endpoint. See the [s3cmd example](https://docs.digitalocean.com/products/spaces/resources/s3cmd/#enter-the-digitalocean-endpoint).

**Describe alternatives you've considered**
Using `s3cmd` in CircleCI.

**Additional context**
This solution will make this orb suitable for many s3-compatible storage services.

**Comment by brivu** [comment]
Hey @atmosx, 

While this definitely sounds like a good idea, this orb is strictly an `aws` orb so installing `s3cmd` would not be possible. An entirely separate orb for `Digital Ocean Spaces` would be necessary. 

-Brian
