### ISSUE TITLE
Use AWS_DEFAULT_REGION instead of AWS_REGION by default

### ISSUE THREAD

**Issue by TheVaan** [CircleCI-Public/aws-s3-orb#27]
**Is your feature request related to a problem? Please describe.**
All circleci/asw-* orbs I checked (cli, ecs, ecr) are using AWS_DEFAULT_REGION as environment variable by default for aws region. Except aws-s3. This orb uses AWS_REGION.

**Describe the solution you'd like**
Instead of overwriting env variable name when running job it would be more intuive using the same env variable the other aws-* are using.

**Comment by brivu** [comment]
Hey @TheVaan, 

I've been working on the other orbs and we've actually decided to change the default environment variable to `AWS_REGION` to be more aligned with the `AWS` documentation. 

Thanks for contributing! 
-Brian
