### ISSUE TITLE
Set S3 upload to run on failure.

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/aws-s3-orb#3]
Original request: https://discuss.circleci.com/t/run-orb-commands-on-fail/34396

**Is your feature request related to a problem? Please describe.**
The "when" attribute is not automatically applied to orb commands, meaning by default these orb commands can not be given the instruction to run "on_failure" as standard job steps are.
https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute

This functionality should likely be extended to all orbs so I have created this feature request here: https://ideas.circleci.com/ideas/CCI-I-1360

**Describe the solution you'd like**
For the time being to allow users to upload important logs, etc, a parameter for setting the "when" condition can be added.

**Describe alternatives you've considered**
Two options described above.

**Additional context**
Slight concern that naming the parameter "when" (if able) may result in compatibility issues in the future if the above feature request is implemented.

**Comment by gmemstr** [comment]
This issue is on hold until https://github.com/CircleCI-Public/aws-cli-orb/issues/54 is addressed

**Comment by KyleTryon** [comment]
Placing into backlog due to low demand. If you are here looking for this feature, please respond!
