### ISSUE TITLE
3.1 version not available via orb registry

### ISSUE THREAD

**Issue by markreynolds2** [CircleCI-Public/aws-s3-orb#42]
**Orb Version**
3.1

**Describe the bug**
Are there plans to release 3.1 officially? The circle hosted version is 3.0 ( https://circleci.com/developer/orbs/orb/circleci/aws-s3 ) and doesn't include the IAM role authentication arn option.
If I try and use the newer release in my pipeline it fails.

**To Reproduce**

Use example code -

  orbs:
    aws-s3: circleci/aws-s3@3.1

Circle gives and error - 

"Cannot find circleci/aws-s3@3.1 in the orb registry. Check that the namespace, orb name and version are correct."

**Expected behavior**

Circleci will use correct version of the orb that supports role-arn as a parameter. 

**Additional context**

**Comment by brivu** [comment]
Hey @markreynolds2, 

I've cut a new release for this orb (v3.1.0) so you should be able to use the `role-arn` parameter now! 

Hope that helps and let me know if there's anything else you need! 

-Brian
