### ISSUE TITLE
Upload to non-amazon S3

### ISSUE THREAD

**Issue by randomairborne** [CircleCI-Public/aws-s3-orb#46]
**Is your feature request related to a problem? Please describe.**
I need to be able to deploy my files to Cloudflare R2. S3 is too expensive.

**Describe the solution you'd like**
I would like an s3-url argument, so i can specify a different upload location.

**Comment by kelvintaywl** [comment]
hi @randomairborne 

thanks for your feature request.
However, this Orb is specifically only for use with AWS S3 buckets.
Perhaps you would like to look into any of these 3rd-party Orbs related to Cloudflare to see if it has your use-case with R2?
https://circleci.com/developer/orbs?query=cloudflare&page=1&pageSize=15

**Comment by randomairborne** [comment]
Unfortunately none of them do, so I will stick to GitHub Actions for now.
