### ISSUE TITLE
Unexpected argument(s): auth

### ISSUE THREAD

**Issue by queglay** [CircleCI-Public/aws-s3-orb#61]
**Orb Version**
The version number of the orb

4.1.0

**Describe the bug**

I get this error when trying to use the orb with a hashicorp terraform circle ci image.
```
Error calling command: 'aws-s3/copy'
Unexpected argument(s): auth
```
**To Reproduce**

Try to use this orb with hashicorp/terraform:1.5.6

**Expected behavior**

The auth argument should not be an unexpected arg when following the docs
https://circleci.com/developer/orbs/orb/circleci/aws-s3#usage-sync_and_copy_with_oidc

**Comment by queglay** [comment]
and removing the auth arg makes it work if I auth outside of the orb...

but then the vscode linter complains about missing an expected arg "auth" which we need to ignore.

**Comment by marboledacci** [comment]
Hi @queglay, the command `aws-s3/copy` doesn't have an auth parameter, the job `aws-s3/copy` is the one with that parameter. If you are creating your own job using the command you have to setup the auth in another command before the copy. You can only use the auth parameter when you are going to use the job copy directly in your workflow.
