### ISSUE TITLE
Unclear that overwrite means --delete for sync command

### ISSUE THREAD

**Issue by MichaelMarner** [CircleCI-Public/aws-s3-orb#7]
**Orb Version**
All versions

**Describe the bug**
This is more a question/discussion about the `overwrite` parameter of the `sync` command. It is not obvious what this parameter actually does.

`aws s3 sync` will _aways_ overwrite files that already exist in the bucket if the files being sync'd are newer.

What the `overwrite` parameter is actually doing is adding the `--delete` flag to the s3 command. This has a _very_ different meaning to what you would expect from overwrite. `--delete` will remove any files that already existed on the bucket but are not in the directory being sync'd. In other words, existing files will be overwritten _regardless_ of the overwrite parameter, but this parameter causes files that may already exist in the bucket to be removed if they are not found in the source directory for the sync command.

Ideally, the `overwrite` parameter would be renamed to `delete` to match what it is actually doing to the `s3 sync command`. 

This unexpected behaviour caused our web app to break due to files being deleted from the bucket when running the sync command with `overwrite: true`.

**Expected behavior**

Either the documentation for this orb makes it clear that `overwrite: true` means `--delete`, or the parameter be renamed to `delete`.

**Comment by smadbe** [comment]
+1. Overwrite is very misleading as it does not overwrite more when enabled, but delete things on the bucket. So people may enable "overwrite" and then have objects deleted, quite dangerous! 
I agree using "delete" as in the AWS CLI would be much more appropriate (and having "overwrite" deprecated)

**Comment by Vivalldi** [comment]
IMO that specific parameter should be removed. We already have the `arguments` parameter where you can specify multiple flags (such as `--acl public-read`)
